name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          sudo apt-get update
          sudo apt-get install -y build-essential cppcheck

      - name: Build the application
        run: |
          echo "Building the application..."
          g++ -o app main.cpp calculate.cpp number_utils.cpp triangle.cpp test_driver.cpp

      - name: Run static analysis
        run: |
          echo "Running static analysis with cppcheck..."
          cppcheck --enable=all .