name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cppcheck

    - name: Build and run main application
      run: |
        g++ -std=c++11 main.cpp calculate.cpp triangle.cpp number_utils.cpp -o calculator
        echo "Running calculator:"

    - name: Run cppcheck
      run: |
        cppcheck --enable=all --inconclusive --std=c++11 *.cpp *.h
